os: linux
dist: jammy
language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - pypy3.7-7.3.9
  - pypy3.8-7.3.9
install:
  - pip install -r tests/requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-erase --cover-package=redminelib
after_success:
  - coveralls
